/* Generated by JSIL v0.8.2 build 30177. See http://jsil.org/ for more information. */ 
'use strict';
var $asm_CSforHTML5App = JSIL.DeclareAssembly("CSforHTML5App, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

/* class ??Csforhtml5App??Component??App??Xaml??Factory */ 

(function $1c0$1c0Csforhtml5App$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.TypeInstantiationHelper)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_CSforHTML5App.CSforHTML5App.App)) ();
  };

  function $1c0$1c0Csforhtml5App$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory_Instantiate () {
    return $T00()['Instantiate']($T01().__Type__);
  };

  JSIL.MakeStaticClass("\u01c0\u01c0Csforhtml5App\u01c0\u01c0Component\u01c0\u01c0App\u01c0\u01c0Xaml\u01c0\u01c0Factory", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:true , Public:true }, "Instantiate", 
      JSIL.MethodSignature.Return($.Object), 
      $1c0$1c0Csforhtml5App$1c0$1c0Component$1c0$1c0App$1c0$1c0Xaml$1c0$1c0Factory_Instantiate
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class ??Csforhtml5App??Component??Mainpage??Xaml??Factory */ 

(function $1c0$1c0Csforhtml5App$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.TypeInstantiationHelper)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_CSforHTML5App.CSforHTML5App.MainPage)) ();
  };

  function $1c0$1c0Csforhtml5App$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory_Instantiate () {
    return $T00()['Instantiate']($T01().__Type__);
  };

  JSIL.MakeStaticClass("\u01c0\u01c0Csforhtml5App\u01c0\u01c0Component\u01c0\u01c0Mainpage\u01c0\u01c0Xaml\u01c0\u01c0Factory", true, [], function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:true , Public:true }, "Instantiate", 
      JSIL.MethodSignature.Return($.Object), 
      $1c0$1c0Csforhtml5App$1c0$1c0Component$1c0$1c0Mainpage$1c0$1c0Xaml$1c0$1c0Factory_Instantiate
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

JSIL.DeclareNamespace("CSforHTML5App");
/* class CSforHTML5App.App */ 

(function App$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Application)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_CSforHTML5App.CSforHTML5App.MainPage)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Window)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm_CSharpXamlForHtml5.CSHTML5.Internal.StartupAssemblyInfo)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.ResourceDictionary)) ();
  };

  function App__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    var content = new ($T01())();
    $T02().Window$Current$value['set_Content'](content);
  };

  function App_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      if (false) {
        $T03().$Cast(this).XamlSourcePath = "CSforHTML5App\\App.xaml";
      }
      $T04().OutputRootPath = "Output\\";
      $T04().OutputAppFilesPath = "app-cshtml5\\app\\";
      $T04().OutputLibrariesPath = "app-cshtml5\\libs\\";
      $T04().OutputResourcesPath = "app-cshtml5\\res\\";
      var resources = new ($T05())();
      this['set_Resources'](resources);
    }
  };

  JSIL.MakeType({
      BaseType: $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Application"), 
      Name: "CSforHTML5App.App", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      App__ctor
    );

    $.Method({Static:false, Public:true }, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      App_InitializeComponent
    );

    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class CSforHTML5App.MainPage */ 

(function MainPage$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Page)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm_mscorlib.System.Object)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm_mscorlib.System.Int32)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ContentControl)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Button)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm_mscorlib.System.Boolean)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Grid)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.RowDefinition)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.RowDefinition))) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ColumnDefinition)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.ColumnDefinition))) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.UserControl)) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.FrameworkElement)) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize($asm_CSharpXamlForHtml5.DotNetForHtml5.Core.TypeFromStringConverters)) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Primitives.ButtonBase)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventHandler)) ();
  };
  var $T12 = function () {
    return ($T12 = JSIL.Memoize($asm_mscorlib.System.Collections.ObjectModel.Collection$b1.Of($asm_CSharpXamlForHtml5.Windows.UI.Xaml.UIElement))) ();
  };
  var $T13 = function () {
    return ($T13 = JSIL.Memoize($asm_CSharpXamlForHtml5.Windows.UI.Xaml.Controls.Panel)) ();
  };

  function MainPage__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
  };

  function MainPage_b_Click (sender, e) {
    var num = ((($T03()['Parse']((($T05().$As(sender))['get_Content']())['toString']()) | 0) + 1) | 0);
    this['eq'](sender, this.b1, num);
    this['eq'](sender, this.b2, num);
    this['eq'](sender, this.b3, num);
    this['eq'](sender, this.b4, num);
    this['eq'](sender, this.b5, num);
    this['eq'](sender, this.b6, num);
  };

  function MainPage_eq (a, b, value) {
    var flag = a === b;
    if (flag) {
      b['set_Content'](value);
    }
  };

  function MainPage_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      if (this !== null) {
        $T07().$Cast(this).XamlSourcePath = "CSforHTML5App\\MainPage.xaml";
      }
      var grid = new ($T08())();
      var item = new ($T09())();
      var item2 = new ($T09())();
      var item3 = new ($T09())();
      (grid['get_RowDefinitions']())['Add'](item);
      (grid['get_RowDefinitions']())['Add'](item2);
      (grid['get_RowDefinitions']())['Add'](item3);
      var item4 = new ($T0B())();
      var item5 = new ($T0B())();
      (grid['get_ColumnDefinitions']())['Add'](item4);
      (grid['get_ColumnDefinitions']())['Add'](item5);
      var button = new ($T05())();
      $T0D().prototype['RegisterName'].call(this, "b1", button);
      button['set_Name']("b1");
      $T08()['SetColumn'](button, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "0")));
      $T08()['SetRow'](button, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "0")));
      button['add_Click']($T11()['New'](this, $thisType.prototype['b_Click'], function () { return JSIL.GetMethodInfo($thisType, "b_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      button['set_Content']($T0F()['ConvertFromInvariantString']($T01().__Type__, "1"));
      var button2 = new ($T05())();
      $T0D().prototype['RegisterName'].call(this, "b2", button2);
      button2['set_Name']("b2");
      $T08()['SetColumn'](button2, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "1")));
      $T08()['SetRow'](button2, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "0")));
      button2['add_Click']($T11()['New'](this, $thisType.prototype['b_Click'], function () { return JSIL.GetMethodInfo($thisType, "b_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      button2['set_Content']($T0F()['ConvertFromInvariantString']($T01().__Type__, "2"));
      var button3 = new ($T05())();
      $T0D().prototype['RegisterName'].call(this, "b3", button3);
      button3['set_Name']("b3");
      $T08()['SetColumn'](button3, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "0")));
      $T08()['SetRow'](button3, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "1")));
      button3['add_Click']($T11()['New'](this, $thisType.prototype['b_Click'], function () { return JSIL.GetMethodInfo($thisType, "b_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      button3['set_Content']($T0F()['ConvertFromInvariantString']($T01().__Type__, "3"));
      var button4 = new ($T05())();
      $T0D().prototype['RegisterName'].call(this, "b4", button4);
      button4['set_Name']("b4");
      $T08()['SetColumn'](button4, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "1")));
      $T08()['SetRow'](button4, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "1")));
      button4['add_Click']($T11()['New'](this, $thisType.prototype['b_Click'], function () { return JSIL.GetMethodInfo($thisType, "b_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      button4['set_Content']($T0F()['ConvertFromInvariantString']($T01().__Type__, "4"));
      var button5 = new ($T05())();
      $T0D().prototype['RegisterName'].call(this, "b5", button5);
      button5['set_Name']("b5");
      $T08()['SetColumn'](button5, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "0")));
      $T08()['SetRow'](button5, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "2")));
      button5['add_Click']($T11()['New'](this, $thisType.prototype['b_Click'], function () { return JSIL.GetMethodInfo($thisType, "b_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      button5['set_Content']($T0F()['ConvertFromInvariantString']($T01().__Type__, "5"));
      var button6 = new ($T05())();
      $T0D().prototype['RegisterName'].call(this, "b6", button6);
      button6['set_Name']("b6");
      $T08()['SetColumn'](button6, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "1")));
      $T08()['SetRow'](button6, $T03().$Cast($T0F()['ConvertFromInvariantString']($T03().__Type__, "2")));
      button6['add_Click']($T11()['New'](this, $thisType.prototype['b_Click'], function () { return JSIL.GetMethodInfo($thisType, "b_Click", new JSIL.MethodSignature(null, [$asm_mscorlib.System.Object, $asm_CSharpXamlForHtml5.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      button6['set_Content']($T0F()['ConvertFromInvariantString']($T01().__Type__, "6"));
      (grid['get_Children']())['Add'](button);
      (grid['get_Children']())['Add'](button2);
      (grid['get_Children']())['Add'](button3);
      (grid['get_Children']())['Add'](button4);
      (grid['get_Children']())['Add'](button5);
      (grid['get_Children']())['Add'](button6);
      this['set_Content'](grid);
      this.b1 = button;
      this.b2 = button2;
      this.b3 = button3;
      this.b4 = button4;
      this.b5 = button5;
      this.b6 = button6;
    }
  };

  JSIL.MakeType({
      BaseType: $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Page"), 
      Name: "CSforHTML5App.MainPage", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainPage__ctor
    );

    $.Method({Static:false, Public:false}, "b_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_b_Click
    );

    $.Method({Static:false, Public:false}, "eq", 
      new JSIL.MethodSignature(null, [
          $.Object, $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button"), 
          $.Object
        ]), 
      MainPage_eq
    );

    $.Method({Static:false, Public:true }, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      MainPage_InitializeComponent
    );

    $['Field']({Static:false, Public:false}, "b1", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "b2", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "b3", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "b4", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "b5", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "b6", $asm_CSharpXamlForHtml5.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

